name: gisola
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - basemap-data=1.3.2
  - basemap-data-hires=1.3.2
  - c-ares=1.17.1
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cycler=0.10.0
  - freetype=2.10.4
  - geos=3.8.1
  - jinja2=2.11.2
  - jpeg=9d
  - kiwisolver=1.3.1
  - krb5=1.17.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib-base=3.3.4
  - ncurses=6.2
  - olefile=0.46
  - openssl=1.1.1k
  - pillow=8.1.0
  - pip=21.0.1
  - proj=7.2.0
  - pyparsing=2.4.7
  - pyproj=3.0.0.post1
  - pyshp=2.1.3
  - python=3.9.2
  - python-dateutil=2.8.1
  - python_abi=3.9
  - readline=8.0
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.34.0
  - tk=8.6.10
  - tornado=6.1
  - tzdata=2021a
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.8
  - pip:
    - basemap==1.3.8
    - chardet==4.0.0
    - decorator==4.4.2
    - future==0.18.2
    - geographiclib==1.50
    - geojson==2.5.0
    - geoparse==2.0.3
    - idna==2.10
    - lxml==4.6.2
    - numpy==1.25.2
    - obspy==1.3.1
    - pandas==1.2.2
    - pytz==2021.1
    - pyyaml==5.4.1
    - requests==2.25.1
    - scipy==1.6.1
    - shapely==1.7.1
    - sqlalchemy==1.3.23
    - tqdm==4.57.0
    - turfpy==0.0.5
    - urllib3==1.26.3
    - version==0.1.0
