MODULE PARAMETERS

      IMPLICIT NONE

      INTEGER, PARAMETER :: MAX_SOURCE_POSITIONS = 100

      INTEGER, PARAMETER :: NUM_OF_TIME_SAMPLES_LOG2 = 13

      INTEGER, PARAMETER :: NUM_OF_TIME_SAMPLES = 2**NUM_OF_TIME_SAMPLES_LOG2

      INTEGER, PARAMETER :: MAX_NUM_OF_TIME_SHIFTS = 200

      INTEGER, PARAMETER :: MIN_TIME_SHIFT = -199

      INTEGER, PARAMETER :: MAX_TIME_SHIFT = IABS(MIN_TIME_SHIFT) + NUM_OF_TIME_SAMPLES

      INTEGER, PARAMETER :: MAX_STATIONS = 16

      INTEGER, PARAMETER :: MAX_CRUSTAL_LAYERS = 200

      REAL, PARAMETER :: PI  = 3.1415926535

      REAL, PARAMETER :: PI2 = 2. * PI

      COMPLEX*16, PARAMETER :: AI = (0., 1.)
END MODULE PARAMETERS

